config/routes.rb
Rails.application.routes.draw do
  get '/', to: 'landing#home', as: 'root'
  
  resources :articles, only: [:index, :show]
  resources :projects, only: [:index, :show]

  get 'about', to: 'landing#about'  

  match "/404", :to => "errors#page_not_found", :via => :all
  match "/500", :to => "errors#server_error", :via => :all

end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/project.rb
class Project < ApplicationRecord
  enum status: [:active, :inactive, :in_progress]
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index 
    @title    = 'Articles'
    @articles = Article.order("published_at").reverse
  end

  def show
    @article     = Article.find_by(slug: params[:id])
    @title       = @article.title
  end
end

app/controllers/errors_controller.rb
class ErrorsController < ApplicationController
  def page_not_found
    render status: 404
  end

  def server_error
    render status: 500
  end
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def landing
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index 
    @title    = 'Projects'
    @projects = Project.order('created_at DESC')
  end

  def show
    @project     = Project.find_by(slug: params[:id])
    @title       = @project.title
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def last_updated
    last_updated = Rails.cache.fetch('last_updated', expires_in: 12.hours) do
      response = HTTParty.get('https://api.github.com/repos/tunkhine126/portfolio-ruby-cms')
      json = JSON.parse(response.body)
      json['pushed_at']
    end
    last_updated.present? ? last_updated : Time.now
  end

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/errors_helper.rb
module ErrorsHelper
end

app/helpers/landing_helper.rb
module LandingHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/articles/index.html.erb
<div class="content-wrapper">
  <h1>Stuff I've written</h1>
  <div class="content">
    <p>Someday I'd like to start writing again.....</p>
    <ul class="articles">
      <% @articles.each do |article| %>
        <li>
          <%= link_to article.title, article_path(article.slug), class: "underlined" %> 
          <time class="code"><%= article.published_at %></time>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/articles/show.html.erb
<div class="content-wrapper">
  <h2><%= @article.title %> <time class="code"><%= @article.published_at %></time></h2>
  <div class="content">
  </div>
</div>

app/views/landing/about.html.erb
<div class="content-wrapper">
  <h1>About Me</h1>
  <div class="content">
    <p>I'm a software engineer based in Atlanta. The majority of my days are spent writing code at <a href="https://newstorycharity.org/" target="_blank">New Story</a>, a housing non-profit that is pioneering solutions to end global homelessness. Check out our Apple documentary film <a href="https://tv.apple.com/us/episode/mexico/umc.cmc.vw8qwc1j4ld8jr3itsc0b3wy" target="_blank">film where the world's first 3D-printed Community was created.</a> 
  </div>
</div>

app/views/landing/home.html.erb
<div>
  <h1>Add default elements</h1>
  <p></p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= @title ? "#{@title} - Tun Khine" : "Tun Khine" %></title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Barlow:wght@100&display=swap" rel="stylesheet">
    
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <%= favicon_link_tag asset_path('fire_flower.ico') %>
  </head>

  <body>

    <div>
      <header>
        <h1><%= link_to "Hi, Im Tun", root_path %></h1>
        <p>Software Engineer. Dad. Generalist.</p>
      </header>
      <p>
        <%= link_to 'About', about_path %>, <%= link_to 'Articles', articles_path %>, <%= link_to 'Projects', projects_path %>
      </p>
    </div>

    <%= yield %>

    <footer>
      Created by Tun Khine. Site last updated on <b><%= last_updated.to_datetime.in_time_zone('Eastern Time (US & Canada)').strftime('%B %e, %Y at %l:%M%P %Z') %></b>. <a href="https://github.com/tunkhine126/portfolio-ruby-cms/commits/master" target="_blank">Changelog</a>.
    </footer>
  </body>
</html>

app/views/projects/index.html.erb
<div class="content-wrapper">
  <h1>Stuff created</h1>
  <div class="content">
    <p>Works in progress.....</p>
    <ul class="projects">
      <% @projects.each do |project| %>
        <li>
          <%= link_to project.title, project_path(project.slug), class: "underlined" %> 
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/projects/show.html.erb
<div class="content-wrapper">
  <h2><%= @project.title %> <time class="code"><%= @project.description %></time></h2>
  <div class="content">

  </div>
</div>